list p=16f84A
#include <P16F84A.INC>
__CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _CP_OFF
    
#define	    BOTAO	PORTA,4	    ;	O BOTÃO ESTÁ ASSOCIADO AO PINO RA0
    
TEMPO1	    EQU	    0X20    ;	ESTAMOS CRIANDO UMA VARIÁVEL TEMPO1 E ARMAZENANDO NO ENDEREÇO HEXA DECIMAL 0X20
TEMPO2	    EQU	    0X21    ;	ESTAMOS CRIANDO UMA VARIÁVEL TEMPO2 E ARMAZENANDO NO ENDEREÇO HEXA DECIMAL 0X21
TEMPO3	    EQU	    0X22    ;	ESTAMOS CRIANDO UMA VARIÁVEL TEMPO3 E ARMAZENANDO NO ENDEREÇO HEXA DECIMAL 0X22

ORG 0x00
    GOTO    INICIO
    
PSECT CODE
    
INICIO:
    BANKSEL	TRISB	    ;	SELECIONANDO O BANCO AONDE SE ENCONTRA O REGISTRADOR TRISB/RB
    MOVLW	B'00000000'	;   ESTOU MOVENDO NUMEROS 0 PARA O REGISTRADOR GENÉRICO W
    MOVWF	TRISB	    ;   ESTOU MOVENDO O REGISTRADOR W PARA O REGISTRADOR TRISB/RB (TODOS OS PINOS DO PORTB/RB SERÃO SAIDA)
    BANKSEL	TRISA	    ;	SELECIONANDO O BANCO AONDE SE ENCONTRA O REGISTRADOR TRISA/RA
    MOVLW	B'00010000'	;   ESTOU MOVENDO NUMEROS 0/1 PARA O REGISTRADOR GENÉRICO W
    MOVWF	TRISA	    ;	ESTOU MOVENDO O REGISTRADOR W PARA O REGISTRADOR TRISA/RA (OS PINOS DAS PORTAS RA0, RA1, RA2 E RA3 SERÃO SAÍDAS E RA4 SERÁ ENTRADA)
    CLRF	PORTB	    ;	ESTOU LIMPANDO O REGISTRADOR PORTB/RB (COLOCANDO TODOS OS PINOS EM NÍVEL LÓGICO BAIXO)
    
MAIN:
    BTFSC	BOTAO	    ;	SE O BOTÃO FOR ZERO, ELE IRÁ PULAR A LINHA DE COMANDO, SE GUINDO PARA A PRÓXIMA (SEGUNDA LINHA)
    GOTO	DESLIGADA	;   IRÁ DESVIAR A INSTRUÇÃO INDO PARA A FUNÇÃO DESLIGAR
    
    BSF		PORTB,0	    ;	VERDE - LIGADO
    BSF		PORTB,5	    ;	VERMELHO - LIGADO
    BSF		PORTB,6	    ;	VERDE - LIGADO
    BSF		PORTA,1	    ;	VERDE - LIGADO
    BSF		PORTA,3	    ;	VERDE - LIGADO
    MOVLW	15	    ;	MOVIMENTA O NÚMERO 15 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 3,750 SEGUNDOS)
    
    BCF		PORTB,0	    ;	DESLIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    ;--------------------------------
    ;	INICIO DO LOOP DA LUZ AMARELA
    ;--------------------------------
    
    BSF		PORTB,1	    ;	AMARELO - LIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    BCF		PORTB,1	    ;	AMARELO - DESLIGADO
    
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    BSF		PORTB,1	    ;	AMARELO - LIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    BCF		PORTB,1	    ;	AMARELO - DESLIGADO
    
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    BSF		PORTB,1	    ;	AMARELO - LIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    BCF		PORTB,1	    ;	AMARELO - DESLIGADO
    
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    BSF		PORTB,1	    ;	AMARELO - LIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    BCF		PORTB,1	    ;	AMARELO - DESLIGADO
    
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    BSF		PORTB,1	    ;	AMARELO - LIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    BCF		PORTB,1	    ;	AMARELO - DESLIGADO
    
    ;-------------------------------
    ;	FINAL DO LOOP DA LUZ AMARELA
    ;-------------------------------
    
    BCF		PORTB,5	    ;	VERMELHO - DESLIGADO
    BCF		PORTB,6	    ;	VERDE - DESLIGADO
    BCF		PORTA,1	    ;	VERDE - DESLIGADO
    BCF		PORTA,3	    ;	VERDE - DESLIGADO
    
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    BSF		PORTB,2	    ;	VERMELHO - LIGADO	
    BSF		PORTB,3	    ;	VERDE - LIGADO
    BSF		PORTB,7	    ;	VERMELHO - LIGADO	
    BSF		PORTA,0	    ;	VERMELHO - LIGADO	
    BSF		PORTA,2	    ;	VERMELHO - LIGADO
    MOVLW	15	    ;	MOVIMENTA O NÚMERO 15 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 3,750 SEGUNDOS)
    BCF		PORTB,3	    ;	
    
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    ;--------------------------------
    ;	INICIO DO LOOP DA LUZ AMARELA
    ;--------------------------------
    
    BSF		PORTB,4	    ;	AMARELO - LIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    BCF		PORTB,4	    ;	AMARELO - DESLIGADO
    
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    BSF		PORTB,4	    ;	AMARELO - LIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    BCF		PORTB,4	    ;	AMARELO - DESLIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    BSF		PORTB,4	    ;	AMARELO - LIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    BCF		PORTB,4	    ;	AMARELO - DESLIGADO
    
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    BSF		PORTB,4	    ;	AMARELO - LIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    BCF		PORTB,4	    ;	AMARELO - DESLIGADO
    
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    BSF		PORTB,4	    ;	AMARELO - LIGADO
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    BCF		PORTB,4	    ;	AMARELO - DESLIGADO
    
    ;-------------------------------
    ;	FINAL DO LOOP DA LUZ AMARELA
    ;-------------------------------
    
    BCF		PORTB,2	    ;	VERMELHO - DESLIGADO	
    BCF		PORTB,3	    ;	VERDE - DESLIGADO
    BCF		PORTB,7	    ;	VERMELHO - DESLIGADO	
    BCF		PORTA,0	    ;	VERMELHO - DESLIGADO	
    BCF		PORTA,2	    ;	VERMELHO - DESLIGADO
    
    MOVLW	5	    ;	MOVIMENTA O NÚMERO 5 PARA O REGISTRADOR GENÉRICO W
    CALL	ATRASO	    ;	ROTINA DE ATRASO E PEGA O NUMERO 15 COMO PARAMETRO (SENDO 1,250 SEGUNDOS)
    
    GOTO	MAIN	    ;   RETORNA A FUNÇÃO PRINCIPAL PARA REPETIR A ROTINA
    
DESLIGADA:
    BANKSEL	PORTB	    ;	ACESSAMOS O BANCO DE MEMÓRIA DA PORTB/RB
    CLRF	PORTB	    ;	E LIMPAMOS (APAGAMOS) OS LEDS
    BANKSEL	PORTA	    ;	ACESSAMOS O BANCO DE MEMÓRIA DA PORTA/RA
    CLRF	PORTA	    ;	E LIMPAMOS (APAGAMOS) OS LEDS
    GOTO	MAIN	    ;	RETORNANDO PARA A ROTINA PRINCIPAL
    
ATRASO:
    MOVWF	TEMPO3	    ;
    
DELAY0:
    MOVLW	250	;   CARREGA O VALOR 250 PARA O REGISTRADOR GENÉRICO W
    MOVWF	TEMPO2	    ;	ARMAZENA O VALOR DO RESGISTRADOR W EM TEMPO2

DELAY1:
    MOVLW	200	;   CARREGA O VALOR 200 PARA O REGISTRADOR GENÉRICO W
    MOVWF	TEMPO1	    ;	ARMAZENA O VALOR DO REGISTRADOR W EM TEMPO1
    
DELAY2:
    NOP	    ;	ATRASO DE UM CICLO DE CLOCK
    NOP	    ;	ATRASO DE UM CICLO DE CLOCK
    DECFSZ	TEMPO1,F	;   DECREMENTA TEMPO1 E VERIFICA SE É ZERO
    GOTO	DELAY2	    ;	SE NÃO FOR ZERO, CONTINUE O ATRASO
    DECFSZ	TEMPO2,F	;   DECREMENTA TEMPO2 E VERIFICA SE É ZERO
    GOTO	DELAY1	    ;	SE NÃO FOR ZERO, CONTINUE O ATRASO
    DECFSZ	TEMPO3,F	;   DECREMENTA TEMPO3 E VERIFICA SE É ZERO
    RETURN	;   RETORNA DA SUB ROTINA DE ATRASO
    
    END	    ;	FIM DO CÓDIGO